name: server

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: 'server'
      - name: Setup Go
        uses: actions/setup-node@v5.0.0
        with:
          go-version: '1.22.0'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v
